import { z } from "zod";

export const formSchema = z.object({
  title: z.string().min(2, {
    message: "Опис повинен складатись не менше ніж з 20 символів",
  }),

  price: z.number().positive({
    message: "Ціна не може бути менше 0",
  }),

  brand: z.string().min(2, {
    message: "Це поле не може бути пустим",
  }),

  ram: z.number().positive({
    message: "Вказано не вірне значення",
  }),

  builtInMemory: z.number().positive({
    message: "Вказано не вірне значення",
  }),

  frontCamera: z.number().positive({
    message: "Вказано не вірне значення",
  }),

  mainCamera: z.number().positive({
    message: "Вказано не вірне значення",
  }),

  screenDiagonal: z.number().positive({
    message: "Вказано не вірне значення",
  }),

  simCount: z.number().positive({
    message: "Вказано не вірне значення",
  }),

  simFormat: z.string().array().nonempty({
    message: "Це поле не може бути пустим",
  }),

  os: z.string().min(1, {
    message: "Це поле не може бути пустим",
  }),

  processorName: z.string().min(2, {
    message: "Це поле не може бути пустим",
  }),

  processorCores: z.string().min(1, {
    message: "Це поле не може бути пустим",
  }),

  battery: z.number().positive({
    message: "Вказано не вірне значення",
  }),

  materials: z.string().min(1, {
    message: "Це поле не може бути пустим",
  }),

  deliverySet: z.string().array().nonempty({
    message: "Це поле не може бути пустим",
  }),

  color: z.string().min(1, {
    message: "Це поле не може бути пустим",
  }),
});

export const defaultValues = {
  title: "",
  price: 0,
  brand: "",
  ram: 0,
  builtInMemory: 0,
  frontCamera: 0,
  mainCamera: 0,
  screenDiagonal: 0,
  simCount: 0,
  simFormat: [],
  os: "",
  processorName: "",
  processorCores: "",
  battery: 0,
  materials: "",
  deliverySet: [],
  color: "",
};

export const mainCharacteristicsInputsData = [
  { key: "ram", label: "Оперативна пам'ять", type: "number", placeholder: "Вкажіть об'єм оперативної пам'яті" },
  {
    key: "builtInMemory",
    label: "Вбудована пам'ять",
    type: "number",
    placeholder: "Вкажіть об'єм вбудованої пам'яті",
  },
  { key: "frontCamera", label: "Фронтальна камера", type: "number", placeholder: "Вкажіть к-ть Мп фронтальної камери" },
  { key: "mainCamera", label: "Основна камера", type: "number", placeholder: "Вкажіть к-ть Мп основної камери" },
  { key: "screenDiagonal", label: "Діагональ екрану", type: "number", placeholder: "Вкажіть діагональ екрану" },
  { key: "simCount", label: "Кількість сім-карт", type: "number", placeholder: "Вкажіть кількість сам-карт" },
  { key: "processorName", label: "Назва процесора", type: "text", placeholder: "Вкажіть назву процесора" },
  {
    key: "processorCores",
    label: "Кількість ядер процесора",
    type: "string",
    placeholder: "Вкажіть кількість ядер процесора",
  },
  { key: "battery", label: "Ємність акумулятора", type: "number", placeholder: "Вкажіть ємність акумулятора" },
] as const;

const colors = [
  { key: "Forest Green", label: "лісовий зелений" },
  { key: "Teal", label: "синьо-зелений" },
  { key: "Orbit Black", label: "глибокий чорний" },
  { key: "Black-Green", label: "чорно-зелений" },
  { key: "Racing Black", label: "рекордовий чорний" },
  { key: "Violet", label: "фіолетовий" },
  { key: "Blue", label: "синій" },
  { key: "Glittery White", label: "блискучий білий" },
  { key: "Storm Black", label: "штормовий чорний" },
  { key: "Khaki", label: "пісочний-хакі" },
  { key: "Wilderness Green", label: "дикий зелений" },
  { key: "Dark Purple", label: "темно-фіолетовий" },
  { key: "Lemon Green", label: "лимонно-зелений" },
  { key: "Platinum", label: "платиновий" },
  { key: "Sandstone Gold", label: "пісочний золотий" },
  { key: "Gray", label: "сірий" },
  { key: "Iceblue", label: "лідно-синій" },
  { key: "Black-Yellow", label: "чорно-жовтий" },
  { key: "Yellow", label: "жовтий" },
  { key: "Dreamy Purple", label: "мрійний фіолетовий" },
  { key: "Silver", label: "сріблястий" },
  { key: "Titan Black", label: "титанічний чорний" },
  { key: "Lightning Gold", label: "блискавичний золотий" },
  { key: "Light Blue", label: "світло-синій" },
  { key: "Black Titanium", label: "чорний титан" },
  { key: "Marble Black", label: "мармуровий чорний" },
  { key: "White", label: "білий" },
  { key: "Peony", label: "піоновий" },
  { key: "Titanium Silver", label: "титанове срібло" },
  { key: "Stellar Shadow", label: "зоряна тінь" },
  { key: "Dark Blue-Black", label: "темно-синьо-чорний" },
  { key: "Pink", label: "рожевий" },
  { key: "Latte", label: "латте" },
  { key: "Blossom Pink", label: "цвітіння рожевий" },
  { key: "Dark Green", label: "темно-зелений" },
  { key: "Ocean Blue", label: "океанський синій" },
  { key: "Frost Blue", label: "морозно-синій" },
  { key: "Green", label: "зелений" },
  { key: "Marshmallow Blue", label: "маршмеллоу синій" },
  { key: "Matte Charcoal", label: "матовий вугільний" },
  { key: "Sand", label: "пісочний" },
  { key: "Twilight Purple", label: "сутінковий фіолетовий" },
  { key: "Lavender", label: "лавандовий" },
  { key: "Victory Gold", label: "переможний золотий" },
  { key: "Titanium Grey", label: "титановий сірий" },
  { key: "Ink Blue", label: "чорнильно-синій" },
  { key: "Voyage Blue", label: "вояж синій" },
  { key: "Aurora Purple", label: "аврора фіолетовий" },
  { key: "Orange", label: "помаранчевий" },
  { key: "Mist Purple", label: "туманний фіолетовий" },
  { key: "Mint Green", label: "м'ятно-зелений" },
  { key: "Ice Blue", label: "лідно-синій" },
  { key: "Blue Sky", label: "блакитне небо" },
  { key: "Grey", label: "сірий" },
  { key: "Midnight Blue", label: "північний синій" },
  { key: "Natural Titanium", label: "натуральний титан" },
  { key: "Aqua Blue", label: "аква-синій" },
  { key: "White Titanium", label: "білий титан" },
  { key: "Metallic Black", label: "металевий чорний" },
  { key: "Bora Purple", label: "бора фіолетовий" },
  { key: "Lilac", label: "ліловий" },
  { key: "Epi Green", label: "епі-зелений" },
  { key: "Glacier Blue", label: "льодовиковий синій" },
  { key: "Startrail Black", label: "зоряний чорний" },
  { key: "Poinciana", label: "пунцово-червоний" },
  { key: "Titan Blue", label: "титаново-синій" },
  { key: "Navy", label: "темно-синій" },
  { key: "Gold", label: "золотий" },
  { key: "Concord Black", label: "конкорд чорний" },
  { key: "Sky Blue", label: "небесно-синій" },
  { key: "Mint", label: "м'ятний" },
  { key: "Star Blue", label: "зоряний синій" },
  { key: "Pearl Pink", label: "перлинно-рожевий" },
  { key: "Ultramarine", label: "ультрамариновий" },
  { key: "Purple", label: "пурпурний" },
  { key: "Starlight", label: "зоряне світло" },
  { key: "Neo Titanium", label: "нео-титан" },
  { key: "Satin Blue", label: "сатиново-синій" },
  { key: "Peach", label: "персиковий" },
  { key: "Midnight Black", label: "північний чорний" },
  { key: "Graphite Grey", label: "графітовий сірий" },
  { key: "Black", label: "чорний" },
  { key: "Desert Titanium", label: "пустельний титан" },
  { key: "Sage Green", label: "шалфейно-зелений" },
  { key: "Sleek Black", label: "гладкий чорний" },
  { key: "Light Green", label: "світло-зелений" },
  { key: "Quartz Grey", label: "кварцовий сірий" },
  { key: "Champagne", label: "шампанське" },
  { key: "Turquoise", label: "бірюзовий" },
  { key: "Frost", label: "морозний" },
];

const colors2 = [
  { key: "black", label: "Чорний" },
  { key: "white", label: "Білий" },
  { key: "red", label: "Червоний" },
  { key: "blue", label: "Синій" },
  { key: "green", label: "Зелений" },
  { key: "yellow", label: "Жовтий" },
  { key: "gray", label: "Сірий" },
  { key: "purple", label: "Фіолетовий" },
  { key: "gold", label: "Золотий" },
  { key: "brown", label: "Коричневий" },
  { key: "orange", label: "Помаранчевий" },
  { key: "beige", label: "Бежевий" },
  { key: "cyan", label: "Блакитний" },
  { key: "burgundy", label: "Бордовий" },
  { key: "turquoise", label: "Бірюзовий" },
  { key: "maroon", label: "Каштановий" },
  { key: "olive", label: "Оливковий" },
  { key: "coral", label: "Кораловий" },
  { key: "lilac", label: "Ліловий" },
  { key: "ivory", label: "Слонова кістка" },
  { key: "khaki", label: "Хакі" },
  { key: "lavender", label: "Лавандовий" },
  { key: "salmon", label: "Лосось" },
  { key: "mint", label: "М'ятний" },
  { key: "cerulean", label: "Лазурний" },
  { key: "Forest Green", label: "лісовий зелений" },
  { key: "Teal", label: "синьо-зелений" },
  { key: "Orbit Black", label: "глибокий чорний" },
  { key: "Black-Green", label: "чорно-зелений" },
  { key: "Racing Black", label: "рекордовий чорний" },
  { key: "Glittery White", label: "блискучий білий" },
  { key: "Storm Black", label: "штормовий чорний" },
  { key: "Khaki", label: "пісочний" },
  { key: "Wilderness Green", label: "дикий зелений" },
  { key: "Dark Purple", label: "темно-фіолетовий" },
  { key: "Lemon Green", label: "лимонно-зелений" },
  { key: "Platinum", label: "платиновий" },
  { key: "Sandstone Gold", label: "пісочний золотий" },
  { key: "Iceblue", label: "лідно-синій" },
  { key: "Black-Yellow", label: "чорно-жовтий" },
  { key: "Dreamy Purple", label: "мрійний фіолетовий" },
  { key: "Silver", label: "сріблястий" },
  { key: "Titan Black", label: "титанічний чорний" },
  { key: "Lightning Gold", label: "блискавичний золотий" },
  { key: "Light Blue", label: "світло-синій" },
  { key: "Black Titanium", label: "чорний титан" },
  { key: "Marble Black", label: "мармуровий чорний" },
  { key: "Peony", label: "піоновий" },
  { key: "Titanium Silver", label: "титанове срібло" },
  { key: "Stellar Shadow", label: "зоряна тінь" },
  { key: "Dark Blue-Black", label: "темно-синьо-чорний" },
  { key: "Pink", label: "рожевий" },
  { key: "Latte", label: "латте" },
  { key: "Blossom Pink", label: "цвітіння рожевий" },
  { key: "Dark Green", label: "темно-зелений" },
  { key: "Ocean Blue", label: "океанський синій" },
  { key: "Frost Blue", label: "морозно-синій" },
  { key: "Marshmallow Blue", label: "маршмеллоу синій" },
  { key: "Matte Charcoal", label: "матовий вугільний" },
  { key: "Twilight Purple", label: "сутінковий фіолетовий" },
  { key: "Lavender", label: "лавандовий" },
  { key: "Victory Gold", label: "переможний золотий" },
  { key: "Midnight", label: "північний чорний" },
  { key: "Titanium Grey", label: "титановий сірий" },
  { key: "Ink Blue", label: "чорнильно-синій" },
  { key: "Voyage Blue", label: "вояж синій" },
  { key: "Aurora Purple", label: "аврора фіолетовий" },
  { key: "Mist Purple", label: "туманний фіолетовий" },
  { key: "Mint Green", label: "м'ятно-зелений" },
  { key: "Blue Sky", label: "блакитне небо" },
  { key: "Midnight Blue", label: "північний синій" },
  { key: "Natural Titanium", label: "натуральний титан" },
  { key: "Aqua Blue", label: "аква-синій" },
  { key: "White Titanium", label: "білий титан" },
  { key: "Metallic Black", label: "металевий чорний" },
  { key: "Bora Purple", label: "бора фіолетовий" },
  { key: "Lilac", label: "ліловий" },
  { key: "Epi Green", label: "епі-зелений" },
  { key: "Glacier Blue", label: "льодовиковий синій" },
  { key: "Startrail Black", label: "зоряний чорний" },
  { key: "Poinciana", label: "пунцово-червоний" },
  { key: "Titan Blue", label: "титаново-синій" },
  { key: "Navy", label: "темно-синій" },
  { key: "Gold", label: "золотий" },
  { key: "Concord Black", label: "конкорд чорний" },
  { key: "Sky Blue", label: "небесно-синій" },
  { key: "Mint", label: "м'ятний" },
  { key: "Star Blue", label: "зоряний синій" },
  { key: "Pearl Pink", label: "перлинно-рожевий" },
  { key: "Ultramarine", label: "ультрамариновий" },
  { key: "Purple", label: "пурпурний" },
  { key: "Starlight", label: "зоряне світло" },
  { key: "Neo Titanium", label: "нео-титан" },
  { key: "Satin Blue", label: "сатиново-синій" },
  { key: "Peach", label: "персиковий" },
  { key: "Graphite Grey", label: "графітовий сірий" },
  { key: "Desert Titanium", label: "пустельний титан" },
  { key: "Sage Green", label: "шалфейно-зелений" },
  { key: "Sleek Black", label: "гладкий чорний" },
  { key: "Light Green", label: "світло-зелений" },
  { key: "Quartz Grey", label: "кварцовий сірий" },
  { key: "Champagne", label: "шампанське" },
  { key: "Turquoise", label: "бірюзовий" },
  { key: "Frost", label: "морозний" },
];

export const mainCharacteristicsSelectData = [
  {
    key: "simFormat",
    label: "Формат сім-карти",
    items: [
      { key: "e-SIM", label: "e-SIM" },
      { key: "Nano-SIM", label: "Nano-SIM" },
      { key: "Mini-SIM", label: "Mini-SIM" },
      { key: "Micro-SIM", label: "Micro-SIM" },
    ],
  },
  {
    key: "os",
    label: "Операційна система",
    items: [
      { key: "Android", label: "Android" },
      { key: "iOS", label: "iOS" },
    ],
  },
  {
    key: "color",
    label: "Колір",
    items: colors,
  },
  {
    key: "materials",
    label: "Матеріал корпуса",
    items: [
      { key: "Алюміній + титан", label: "Алюміній + титан" },
      { key: "Титан + скло", label: "Титан + скло" },
      { key: "Алюміній", label: "Алюміній" },
      { key: "Алюміній + скло", label: "Алюміній + скло" },
      { key: "Пластик", label: "Пластик" },
      { key: "Пластик + скло", label: "Пластик + скло" },
      { key: "Метал + пластик", label: "Метал + пластик" },
      { key: "Пластик + гума", label: "Пластик + гума" },
      { key: "Пластик + метал", label: "Пластик + метал" },
      { key: "Неіржав.сталь + скло + пластик + гума", label: "Неіржав.сталь + скло + пластик + гума" },
      { key: "Метал + скло", label: "Метал + скло" },
      { key: "Полікарбонат", label: "Полікарбонат" },
      { key: "Метал + Скло + Пластик", label: "Метал + Скло + Пластик" },
      { key: "Алюміній + Пластик + Скло", label: "Алюміній + Пластик + Скло" },
      { key: "Метал + Екошкіра", label: "Метал + Екошкіра" },
      { key: "Пластик + метал + гума", label: "Пластик + метал + гума" },
      { key: "Скло", label: "Скло" },
    ],
  },
  {
    key: "deliverySet",
    label: "Комплект постачання",
    items: [
      // { key: "phone", label: "Телефон" },
      // { key: "charger", label: "Зарядний пристрій" },
      // { key: "cable", label: "Кабель" },
      // { key: "headphones", label: "Навушники" },
      // { key: "manual", label: "Інструкція" },
      // { key: "box", label: "Коробка" },
      // { key: "docs", label: "Документація" },

      { key: "Телефон", label: "Телефон" },
      { key: "Кабель для заряджання", label: "Кабель для заряджання" },
      { key: "Зарядний пристрій", label: "Зарядний пристрій" },
      { key: "Скріпка для виймання СІМ-карти", label: "Скріпка для виймання СІМ-карти" },
      { key: "Чохол", label: "Чохол" },
      { key: "Захисне скло", label: "Захисне скло" },
      { key: "Захисна плівка", label: "Захисна плівка" },
      { key: "Гарантійний талон", label: "Гарантійний талон" },
      { key: "Документація", label: "Документація" },
      { key: "Док-станція", label: "Док-станція" },
      { key: "Перехідник OTG", label: "Перехідник OTG" },
      { key: "Викрутка для задньої кришки", label: "Викрутка для задньої кришки" },
      { key: "Кабель OTG", label: "Кабель OTG" },
      { key: "Акумуляторна батарея", label: "Акумуляторна батарея" },
      { key: "Антена", label: "Антена" },
      { key: "Бездротовий зарядний пристрій", label: "Бездротовий зарядний пристрій" },
      { key: "Стилус", label: "Стилус" },
      { key: "Гарнітура", label: "Гарнітура" },
      { key: "Кабель для синхронізації", label: "Кабель для синхронізації" },
      { key: "Перехідник USB Type-C - USB", label: "Перехідник USB Type-C - USB" },
      { key: "ТелефонАкумуляторна батарея", label: "ТелефонАкумуляторна батарея" },
      { key: "Ремінець", label: "Ремінець" },
      { key: "Карта пам'яті", label: "Карта пам'яті" },
    ],
  },
] as const;
