export const PHONE_BRAND_NAMES = [
  { label_ua: "IPhone", label_en: "IPhone", key: "Apple" },
  { label_ua: "Samsung", label_en: "Samsung", key: "samsung" },
  { label_ua: "Xiaomi", label_en: "Xiaomi", key: "xiaomi" },
  { label_ua: "One Plus", label_en: "One Plus", key: "oneplus" },
  { label_ua: "Google Pixel", label_en: "Google Pixel", key: "google pixel" },
  { label_ua: "Motorola", label_en: "Motorola", key: "motorola" },
  { label_ua: "Nokia", label_en: "Nokia", key: "nokia" },
  { label_ua: "Poco", label_en: "Poco", key: "poco" },
  { label_ua: "Oppo", label_en: "Oppo", key: "oppo" },
  { label_ua: "Realme", label_en: "Realme", key: "realme" },
  { label_ua: "Huawei", label_en: "Huawei", key: "huawei" },
  { label_ua: "Honor", label_en: "Honor", key: "honor" },
  { label_ua: "Meizu", label_en: "Meizu", key: "meizu" },
  { label_ua: "Sony", label_en: "Sony", key: "sony" },
  { label_ua: "Vivo", label_en: "Vivo", key: "vivo" },
  { label_ua: "Nubia", label_en: "Nubia", key: "nubia" },
  { label_ua: "Tecno", label_en: "Tecno", key: "tecno spark" },
  { label_ua: "Zte", label_en: "Zte", key: "zte" },
  { label_ua: "Infinix", label_en: "Infinix", key: "infinix" },
  { label_ua: "Blackview", label_en: "Blackview", key: "blackview" },
  { label_ua: "Sigma", label_en: "Sigma", key: "sigma" },
  { label_ua: "Hmd", label_en: "Hmd", key: "hmd" },
  { label_ua: "Gigaset", label_en: "Gigaset", key: "gigaset" },
  { label_ua: "Oukitel", label_en: "Oukitel", key: "oukitel" },
  { label_ua: "Ulefone", label_en: "Ulefone", key: "ulefone" },
  { label_ua: "Asus", label_en: "Asus", key: "asus" },
  { label_ua: "Doogee", label_en: "Doogee", key: "doogee" },
  { label_ua: "Myphone", label_en: "Myphone", key: "myphone" },
  { label_ua: "Evelatus", label_en: "Evelatus", key: "evelatus" },
  { label_ua: "Agm", label_en: "Agm", key: "agm" },
  { label_ua: "Doro", label_en: "Doro", key: "doro" },
  { label_ua: "Nomi", label_en: "Nomi", key: "nomi" },
  { label_ua: "Ergo", label_en: "Ergo", key: "ergo" },
  { label_ua: "Beafon", label_en: "Beafon", key: "beafon" },
  { label_ua: "Emporia", label_en: "Emporia", key: "emporia" },
  { label_ua: "Swisstone", label_en: "Swisstone", key: "swisstone" },
  { label_ua: "Cmf", label_en: "Cmf", key: "cmf" },
  { label_ua: "HMD", label_en: "HMD", key: "HMD" },
  {
    label_ua: "Nothing Phone",
    label_en: "Nothing Phone",
    key: "nothing phone",
  },
  { label_ua: "Crosscall", label_en: "Crosscall", key: "crosscall" },
  { label_ua: "Jablocom", label_en: "Jablocom", key: "jablocom" },
];

const PHONE_MATHERIAL_NAMES = [
  "Алюміній + титан",
  "Титан + скло",
  "Алюміній",
  "Алюміній + скло",
  "Пластик",
  "Пластик + скло",
  "Метал + пластик",
  "Пластик + гума",
  "Пластик + метал",
  "Неіржав.сталь + скло + пластик + гума",
  "Метал + скло",
  "Полікарбонат",
  "Метал + Скло + Пластик",
  "Алюміній + Пластик + Скло",
  "Метал + Екошкіра",
  "Пластик + метал + гума",
  "Скло",
];

const PHONE_COLORS = [
  {
    key: "Forest Green",
    label_ua: "лісовий зелений",
    label_en: "Forest Green",
  },
  { key: "Teal", label_ua: "синьо-зелений", label_en: "Teal" },
  { key: "Orbit Black", label_ua: "глибокий чорний", label_en: "Orbit Black" },
  { key: "Black-Green", label_ua: "чорно-зелений", label_en: "Black-Green" },
  {
    key: "Racing Black",
    label_ua: "рекордовий чорний",
    label_en: "Racing Black",
  },
  { key: "Violet", label_ua: "фіолетовий", label_en: "Violet" },
  { key: "Blue", label_ua: "синій", label_en: "Blue" },
  {
    key: "Glittery White",
    label_ua: "блискучий білий",
    label_en: "Glittery White",
  },
  { key: "Storm Black", label_ua: "штормовий чорний", label_en: "Storm Black" },
  { key: "Khaki", label_ua: "пісочний", label_en: "Khaki" },
  {
    key: "Wilderness Green",
    label_ua: "дикий зелений",
    label_en: "Wilderness Green",
  },
  { key: "Dark Purple", label_ua: "темно-фіолетовий", label_en: "Dark Purple" },
  { key: "Lemon Green", label_ua: "лимонно-зелений", label_en: "Lemon Green" },
  { key: "Platinum", label_ua: "платиновий", label_en: "Platinum" },
  {
    key: "Sandstone Gold",
    label_ua: "пісочний золотий",
    label_en: "Sandstone Gold",
  },
  { key: "Gray", label_ua: "сірий", label_en: "Gray" },
  { key: "Iceblue", label_ua: "лідно-синій", label_en: "Iceblue" },
  { key: "Black-Yellow", label_ua: "чорно-жовтий", label_en: "Black-Yellow" },
  { key: "Yellow", label_ua: "жовтий", label_en: "Yellow" },
  {
    key: "Dreamy Purple",
    label_ua: "мрійний фіолетовий",
    label_en: "Dreamy Purple",
  },
  { key: "Silver", label_ua: "сріблястий", label_en: "Silver" },
  {
    key: "Titan Black",
    label_ua: "титанічний чорний",
    label_en: "Titan Black",
  },
  {
    key: "Lightning Gold",
    label_ua: "блискавичний золотий",
    label_en: "Lightning Gold",
  },
  { key: "Light Blue", label_ua: "світло-синій", label_en: "Light Blue" },
  {
    key: "Black Titanium",
    label_ua: "чорний титан",
    label_en: "Black Titanium",
  },
  {
    key: "Marble Black",
    label_ua: "мармуровий чорний",
    label_en: "Marble Black",
  },
  { key: "White", label_ua: "білий", label_en: "White" },
  { key: "Peony", label_ua: "піоновий", label_en: "Peony" },
  {
    key: "Titanium Silver",
    label_ua: "титанове срібло",
    label_en: "Titanium Silver",
  },
  {
    key: "Stellar Shadow",
    label_ua: "зоряна тінь",
    label_en: "Stellar Shadow",
  },
  {
    key: "Dark Blue-Black",
    label_ua: "темно-синьо-чорний",
    label_en: "Dark Blue-Black",
  },
  { key: "Pink", label_ua: "рожевий", label_en: "Pink" },
  { key: "Latte", label_ua: "латте", label_en: "Latte" },
  {
    key: "Blossom Pink",
    label_ua: "цвітіння рожевий",
    label_en: "Blossom Pink",
  },
  { key: "Dark Green", label_ua: "темно-зелений", label_en: "Dark Green" },
  { key: "Ocean Blue", label_ua: "океанський синій", label_en: "Ocean Blue" },
  { key: "Frost Blue", label_ua: "морозно-синій", label_en: "Frost Blue" },
  { key: "Green", label_ua: "зелений", label_en: "Green" },
  {
    key: "Marshmallow Blue",
    label_ua: "маршмеллоу синій",
    label_en: "Marshmallow Blue",
  },
  {
    key: "Matte Charcoal",
    label_ua: "матовий вугільний",
    label_en: "Matte Charcoal",
  },
  { key: "Sand", label_ua: "пісочний", label_en: "Sand" },
  {
    key: "Twilight Purple",
    label_ua: "сутінковий фіолетовий",
    label_en: "Twilight Purple",
  },
  { key: "Lavender", label_ua: "лавандовий", label_en: "Lavender" },
  {
    key: "Victory Gold",
    label_ua: "переможний золотий",
    label_en: "Victory Gold",
  },
  { key: "Midnight", label_ua: "північний чорний", label_en: "Midnight" },
  {
    key: "Titanium Grey",
    label_ua: "титановий сірий",
    label_en: "Titanium Grey",
  },
  { key: "Ink Blue", label_ua: "чорнильно-синій", label_en: "Ink Blue" },
  { key: "Voyage Blue", label_ua: "вояж синій", label_en: "Voyage Blue" },
  {
    key: "Aurora Purple",
    label_ua: "аврора фіолетовий",
    label_en: "Aurora Purple",
  },
  { key: "Orange", label_ua: "помаранчевий", label_en: "Orange" },
  {
    key: "Mist Purple",
    label_ua: "туманний фіолетовий",
    label_en: "Mist Purple",
  },
  { key: "Mint Green", label_ua: "м'ятно-зелений", label_en: "Mint Green" },
  { key: "Ice Blue", label_ua: "лідно-синій", label_en: "Ice Blue" },
  { key: "Blue Sky", label_ua: "блакитне небо", label_en: "Blue Sky" },
  { key: "Grey", label_ua: "сірий", label_en: "Grey" },
  {
    key: "Midnight Blue",
    label_ua: "північний синій",
    label_en: "Midnight Blue",
  },
  {
    key: "Natural Titanium",
    label_ua: "натуральний титан",
    label_en: "Natural Titanium",
  },
  { key: "Aqua Blue", label_ua: "аква-синій", label_en: "Aqua Blue" },
  {
    key: "White Titanium",
    label_ua: "білий титан",
    label_en: "White Titanium",
  },
  {
    key: "Metallic Black",
    label_ua: "металевий чорний",
    label_en: "Metallic Black",
  },
  { key: "Bora Purple", label_ua: "бора фіолетовий", label_en: "Bora Purple" },
  { key: "Lilac", label_ua: "ліловий", label_en: "Lilac" },
  { key: "Epi Green", label_ua: "епі-зелений", label_en: "Epi Green" },
  {
    key: "Glacier Blue",
    label_ua: "льодовиковий синій",
    label_en: "Glacier Blue",
  },
  {
    key: "Startrail Black",
    label_ua: "зоряний чорний",
    label_en: "Startrail Black",
  },
  { key: "Poinciana", label_ua: "пунцово-червоний", label_en: "Poinciana" },
  { key: "Titan Blue", label_ua: "титаново-синій", label_en: "Titan Blue" },
  { key: "Navy", label_ua: "темно-синій", label_en: "Navy" },
  { key: "Gold", label_ua: "золотий", label_en: "Gold" },
  {
    key: "Concord Black",
    label_ua: "конкорд чорний",
    label_en: "Concord Black",
  },
  { key: "Sky Blue", label_ua: "небесно-синій", label_en: "Sky Blue" },
  { key: "Mint", label_ua: "м'ятний", label_en: "Mint" },
  { key: "Star Blue", label_ua: "зоряний синій", label_en: "Star Blue" },
  { key: "Pearl Pink", label_ua: "перлинно-рожевий", label_en: "Pearl Pink" },
  { key: "Ultramarine", label_ua: "ультрамариновий", label_en: "Ultramarine" },
  { key: "Purple", label_ua: "пурпурний", label_en: "Purple" },
  { key: "Starlight", label_ua: "зоряне світло", label_en: "Starlight" },
  { key: "Neo Titanium", label_ua: "нео-титан", label_en: "Neo Titanium" },
  { key: "Satin Blue", label_ua: "сатиново-синій", label_en: "Satin Blue" },
  { key: "Peach", label_ua: "персиковий", label_en: "Peach" },
  {
    key: "Midnight Black",
    label_ua: "північний чорний",
    label_en: "Midnight Black",
  },
  {
    key: "Graphite Grey",
    label_ua: "графітовий сірий",
    label_en: "Graphite Grey",
  },
  { key: "Black", label_ua: "чорний", label_en: "Black" },
  {
    key: "Desert Titanium",
    label_ua: "пустельний титан",
    label_en: "Desert Titanium",
  },
  { key: "Sage Green", label_ua: "шалфейно-зелений", label_en: "Sage Green" },
  { key: "Sleek Black", label_ua: "гладкий чорний", label_en: "Sleek Black" },
  { key: "Light Green", label_ua: "світло-зелений", label_en: "Light Green" },
  { key: "Quartz Grey", label_ua: "кварцовий сірий", label_en: "Quartz Grey" },
  { key: "Champagne", label_ua: "шампанське", label_en: "Champagne" },
  { key: "Turquoise", label_ua: "бірюзовий", label_en: "Turquoise" },
  { key: "Frost", label_ua: "морозний", label_en: "Frost" },
];

const PHONE_MATHERIALS = [
  {
    key: "Алюміній + титан",
    label_ua: "Алюміній + титан",
    label_en: "Aluminum + titanium",
  },
  {
    key: "Титан + скло",
    label_ua: "Титан + скло",
    label_en: "Titanium + glass",
  },
  { key: "Алюміній", label_ua: "Алюміній", label_en: "Aluminum" },
  {
    key: "Алюміній + скло",
    label_ua: "Алюміній + скло",
    label_en: "Aluminum + glass",
  },
  { key: "Пластик", label_ua: "Пластик", label_en: "Plastic" },
  {
    key: "Пластик + скло",
    label_ua: "Пластик + скло",
    label_en: "Plastic + glass",
  },
  {
    key: "Метал + пластик",
    label_ua: "Метал + пластик",
    label_en: "Metal + plastic",
  },
  {
    key: "Пластик + гума",
    label_ua: "Пластик + гума",
    label_en: "Plastic + rubber",
  },
  {
    key: "Пластик + метал",
    label_ua: "Пластик + метал",
    label_en: "Plastic + metal",
  },
  {
    key: "Неіржав.сталь + скло + пластик + гума",
    label_ua: "Неіржав.сталь + скло + пластик + гума",
    label_en: "Stainless steel + glass + plastic + rubber",
  },
  {
    key: "Метал + скло",
    label_ua: "Метал + скло",
    label_en: "Metal + glass",
  },
  {
    key: "Полікарбонат",
    label_ua: "Полікарбонат",
    label_en: "Polycarbonate",
  },
  {
    key: "Метал + Скло + Пластик",
    label_ua: "Метал + Скло + Пластик",
    label_en: "Metal + glass + plastic",
  },
  {
    key: "Алюміній + Пластик + Скло",
    label_ua: "Алюміній + Пластик + Скло",
    label_en: "Aluminum + plastic + glass",
  },
  {
    key: "Метал + Екошкіра",
    label_ua: "Метал + Екошкіра",
    label_en: "Metal + eco-leather",
  },
  {
    key: "Пластик + метал + гума",
    label_ua: "Пластик + метал + гума",
    label_en: "Plastic + metal + rubber",
  },
  { key: "Скло", label_ua: "Скло", label_en: "Glass" },
];

const DELIVERY_SET_ITEMS = [
  "Кабель для заряджання",
  "Перехідник OTG",
  "Док-станція",
  "Телефон",
  "Зарядний пристрій",
  "Викрутка для задньої кришки",
  "Кабель OTG",
  "Скріпка для виймання СІМ-карти",
  "Документація",
  "Акумуляторна батарея",
  "Гарантійний талон",
  "Антена",
  "Бездротовий зарядний пристрій",
  "Чохол",
  "Стилус",
  "Гарнітура",
  "Кабель для синхронізації",
  "Захисне скло",
  "Перехідник USB Type-C - USB",
  "ТелефонАкумуляторна батарея",
  "Захисна плівка",
  "Ремінець",
  "Карта пам'яті",
];

const DELIVERY_SET = [
  {
    key: "Кабель для заряджання",
    label_ua: "Кабель для заряджання",
    label_en: "Charging Cable",
  },
  {
    key: "Перехідник OTG",
    label_ua: "Перехідник OTG",
    label_en: "OTG Adapter",
  },
  { key: "Док-станція", label_ua: "Док-станція", label_en: "Docking Station" },
  { key: "Телефон", label_ua: "Телефон", label_en: "Phone" },
  {
    key: "Зарядний пристрій",
    label_ua: "Зарядний пристрій",
    label_en: "Charger",
  },
  {
    key: "Викрутка для задньої кришки",
    label_ua: "Викрутка для задньої кришки",
    label_en: "Screwdriver for Back Cover",
  },
  { key: "Кабель OTG", label_ua: "Кабель OTG", label_en: "OTG Cable" },
  {
    key: "Скріпка для виймання СІМ-карти",
    label_ua: "Скріпка для виймання СІМ-карти",
    label_en: "SIM Card Ejector Pin",
  },
  { key: "Документація", label_ua: "Документація", label_en: "Documentation" },
  {
    key: "Акумуляторна батарея",
    label_ua: "Акумуляторна батарея",
    label_en: "Battery",
  },
  {
    key: "Гарантійний талон",
    label_ua: "Гарантійний талон",
    label_en: "Warranty Card",
  },
  { key: "Антена", label_ua: "Антена", label_en: "Antenna" },
  {
    key: "Бездротовий зарядний пристрій",
    label_ua: "Бездротовий зарядний пристрій",
    label_en: "Wireless Charger",
  },
  { key: "Чохол", label_ua: "Чохол", label_en: "Case" },
  { key: "Стилус", label_ua: "Стилус", label_en: "Stylus" },
  { key: "Гарнітура", label_ua: "Гарнітура", label_en: "Headset" },
  {
    key: "Кабель для синхронізації",
    label_ua: "Кабель для синхронізації",
    label_en: "Sync Cable",
  },
  {
    key: "Захисне скло",
    label_ua: "Захисне скло",
    label_en: "Screen Protector",
  },
  {
    key: "Перехідник USB Type-C - USB",
    label_ua: "Перехідник USB Type-C - USB",
    label_en: "USB Type-C to USB Adapter",
  },
  {
    key: "ТелефонАкумуляторна батарея",
    label_ua: "ТелефонАкумуляторна батарея",
    label_en: "Phone Battery",
  },
  {
    key: "Захисна плівка",
    label_ua: "Захисна плівка",
    label_en: "Protective Film",
  },
  { key: "Ремінець", label_ua: "Ремінець", label_en: "Strap" },
  { key: "Карта пам'яті", label_ua: "Карта пам'яті", label_en: "Memory Card" },
];

// ['Алюміній + титан' 'Титан + скло' 'Алюміній' 'Алюміній + скло' 'Пластик'
//     'Пластик + скло' 'Метал + пластик' 'Пластик + гума' 'Пластик + метал'
//     'Неіржавка сталь + скло + пластик + гума' 'Метал + скло' 'Полікарбонат'
//     'Метал + Скло + Пластик' 'Алюміній + Пластик + Скло' 'Метал + Екошкіра'
//     'Пластик + метал + гума' 'Скло']

export const productInputFilters = [
  {
    key: "brand",
    label_ua: "Бренд",
    label_en: "Brand",
    items: PHONE_BRAND_NAMES,
  },
  {
    key: "screenDiagonal",
    label_ua: "Діагональ екрану",
    label_en: "Screen diagonal",
    items: [
      { key: "0-4.59", label_ua: "4.59 і менше", label_en: "4.59 or less" },
      { key: "4.6-5", label_ua: "4.6 - 5", label_en: "4.6 - 5" },
      { key: "5.01-5.5", label_ua: "5.01 - 5.5", label_en: "5.01 - 5.5" },
      { key: "5.55-6", label_ua: "5.55 - 6", label_en: "5.55 - 6" },
      { key: "6.01-6.49", label_ua: "6.01 - 6.49", label_en: "6.01 - 6.49" },
      { key: "6.5-6.9", label_ua: "6.5 - 6.9", label_en: "6.5 - 6.9" },
      { key: "7-99", label_ua: "7 і більше", label_en: "7 or more" },
    ],
  },
  {
    key: "ram",
    label_ua: "Оперативна пам'ять",
    label_en: "RAM",
    items: [
      { key: "0-2", label_ua: "2 ГБ і менше", label_en: "2 GB or less" },
      { key: "3-3", label_ua: "3 ГБ", label_en: "3 GB" },
      { key: "4-4", label_ua: "4 ГБ", label_en: "4 GB" },
      { key: "6-6", label_ua: "6 ГБ", label_en: "6 GB" },
      { key: "8-8", label_ua: "8 ГБ", label_en: "8 GB" },
      { key: "12-12", label_ua: "12 ГБ", label_en: "12 GB" },
      { key: "14-14", label_ua: "14 ГБ", label_en: "14 GB" },
      { key: "16-16", label_ua: "16 ГБ", label_en: "16 GB" },
      { key: "17-17", label_ua: "17 ГБ", label_en: "17 GB" },
      { key: "18-18", label_ua: "18 ГБ", label_en: "18 GB" },
      { key: "24-24", label_ua: "24 ГБ", label_en: "24 GB" },
      { key: "32-32", label_ua: "32 ГБ", label_en: "32 GB" },
    ],
  },
  {
    key: "builtInMemory",
    label_ua: "Вбудована пам'ять",
    label_en: "Built-in memory",
    items: [
      { key: "0-16", label_ua: "16 ГБ і менше", label_en: "16 GB or less" },
      { key: "32-32", label_ua: "32 ГБ", label_en: "32 GB" },
      { key: "64-64", label_ua: "64 ГБ", label_en: "64 GB" },
      { key: "128-128", label_ua: "128 ГБ", label_en: "128 GB" },
      { key: "256-256", label_ua: "256 ГБ", label_en: "256 GB" },
      { key: "512-512", label_ua: "512 ГБ", label_en: "512 GB" },
      { key: "1000-1000", label_ua: "1 ТБ", label_en: "1 TB" },
    ],
  },
  {
    key: "battery",
    label_ua: "Ємність акумулятора",
    label_en: "Battery capacity",
    items: [
      {
        key: "0-2999",
        label_ua: "2999 мА*год і менше",
        label_en: "2999 mA*h or less",
      },
      {
        key: "3000-3999",
        label_ua: "3000 - 3999 мА*год",
        label_en: "3000 - 3999 mA*h",
      },
      {
        key: "4000-4999",
        label_ua: "4000 - 4999 мА*год",
        label_en: "4000 - 4999 mA*h",
      },
      {
        key: "5000-5999",
        label_ua: "5000 - 5999 мА*год",
        label_en: "5000 - 5999 mA*h",
      },
      {
        key: "6000-9999",
        label_ua: "6000 мА*год і більше",
        label_en: "6000 mA*h or more",
      },
    ],
  },
  {
    key: "mainCamera",
    label_ua: "Основна камера",
    label_en: "Main camera",
    items: [
      { key: "0-15", label_ua: "15 Мп і менше", label_en: "15 Mp or less" },
      { key: "16-20.9", label_ua: "16 - 20.9 Мп", label_en: "16 - 20.9 Mp" },
      { key: "21-48", label_ua: "21 - 48 Мп", label_en: "21 - 48 Mp" },
      { key: "49-99", label_ua: "49 - 64 Мп", label_en: "49 - 64 Mp" },
      {
        key: "100-999",
        label_ua: "100 Мп і більше",
        label_en: "100 Mp or more",
      },
    ],
  },
  {
    key: "frontCamera",
    label_ua: "Фронтальна камера",
    label_en: "Front camera",
    items: [
      { key: "0-8", label_ua: "8 Мп і менше", label_en: "8 Mp or less" },
      { key: "9-16", label_ua: "9 - 16 Мп", label_en: "9 - 16 Mp" },
      { key: "17-20", label_ua: "17 - 20 Мп", label_en: "17 - 20 Mp" },
      { key: "21-30", label_ua: "21 - 30 Мп", label_en: "21 - 30 Mp" },
      { key: "31-39", label_ua: "31 - 39 Мп", label_en: "31 - 39 Mp" },
      { key: "40-99", label_ua: "40 Мп і більше", label_en: "40 Mp or more" },
    ],
  },
  {
    key: "processorName",
    label_ua: "Назва процесора",
    label_en: "Processor name",
    items: [
      { key: "Apple", label_ua: "Apple", label_en: "Apple" },
      { key: "MediaTek", label_ua: "MediaTek", label_en: "MediaTek" },
      {
        key: "Qualcomm Snapdragon",
        label_ua: "Qualcomm Snapdragon",
        label_en: "Qualcomm Snapdragon",
      },
      {
        key: "Samsung Exynos",
        label_ua: "Samsung Exynos",
        label_en: "Samsung Exynos",
      },
      { key: "Unisoc", label_ua: "Unisoc", label_en: "Unisoc" },
      {
        key: "HiSilicon Kirin",
        label_ua: "HiSilicon Kirin",
        label_en: "HiSilicon Kirin",
      },
      { key: "Spreadtrum", label_ua: "Spreadtrum", label_en: "Spreadtrum" },
    ],
  },
  {
    key: "os",
    label_ua: "Операційна система",
    label_en: "Operating system",
    items: [
      { key: "Android", label_ua: "Android", label_en: "Android" },
      { key: "iOS", label_ua: "iOS", label_en: "iOS" },
    ],
  },
  {
    key: "simCount",
    label_ua: "Кількість SIM-карток",
    label_en: "Number of SIM-cards",
    items: [
      { key: "1-1", label_ua: 1, label_en: 1 },
      { key: "2-2", label_ua: 2, label_en: 2 },
      { key: "3-3", label_ua: 3, label_en: 3 },
      { key: "4-4", label_ua: 4, label_en: 4 },
    ],
  },

  {
    key: "simFormat",
    label_ua: "Формат SIM-картки",
    label_en: "SIM-card format",
    items: [
      { key: "e-SIM", label_ua: "e-SIM", label_en: "e-SIM" },
      { key: "Nano-SIM", label_ua: "Nano-SIM", label_en: "Nano-SIM" },
      { key: "Mini-SIM", label_ua: "Mini-SIM", label_en: "Mini-SIM" },
      { key: "Micro-SIM", label_ua: "Micro-SIM", label_en: "Micro-SIM" },
    ],
  },
  {
    key: "materials",
    label_ua: "Матеріал корпусу",
    label_en: "Case material",
    items: PHONE_MATHERIALS,
  },
  {
    key: "color",
    label_ua: "Колір",
    label_en: "Color",
    items: PHONE_COLORS,
  },

  {
    key: "deliverySet",
    label_ua: "Комплект постачання",
    label_en: "Delivery set",
    items: DELIVERY_SET,
  },
] as const;
