query FindProfile {
  findProfile {
    id
    username
    displayName
    email
    avatar

    city
    street
    postOffice

    createdAt
    updatedAt

    favorites {
      product {
        id
        title
        price
        brand
        frontCamera
        mainCamera
        ram
        color
        builtInMemory
        processorName
        processorCores
        os
        deliverySet
        materials
        simCount
        simFormat
        images
        battery
        screenDiagonal
        createdAt
        updatedAt
      }
    }
    cart {
      id
      count
      product {
        id
        title
        price
        brand
        frontCamera
        mainCamera
        ram
        color
        builtInMemory
        processorName
        processorCores
        os
        deliverySet
        materials
        simCount
        simFormat
        images
        battery
        screenDiagonal
        createdAt
        updatedAt
      }
    }
    reviews {
      id
      text
      rating
      createdAt
      product {
        id
        images
        brand
        ram
        builtInMemory
        color
      }
      user {
        id
        displayName
        avatar
      }
    }
    # orders {
    #   id
    # }
  }
}
