query FindProfile {
  findProfile {
    id
    username
    displayName
    email
    avatar

    city
    street
    postOffice

    createdAt
    updatedAt

    favorites {
      product {
        ...ProductFragment
      }
    }
    cart {
      id
      count
      product {
        ...ProductFragment
      }
    }
    reviews {
      id
      text
      rating
      createdAt
      product {
        id
        images
        brand
        ram
        builtInMemory
        color
      }
      user {
        id
        displayName
        avatar
      }
    }
    orders {
      id
      status
      total
      createdAt
      items {
        id
        price
        quantity
        product {
          ...ProductFragment
        }
      }
    }
  }
}
