// 'use client'
import type { Metadata } from 'next'
import { useTheme } from 'next-themes'
import { Montserrat } from 'next/font/google'
import { Toaster, ToasterProps } from 'sonner'
import { NextIntlClientProvider } from 'next-intl'
import { getLocale, getMessages } from 'next-intl/server'

import '../styles/global.css'
import Footer from '@/components/layout/footer/Footer'
import Header from '@/components/layout/header/Header'
import { ThemeProvider } from '@/providers/ThemeProvider'
import AppProgressBar from '@/components/layout/AppProgressBar'
import ApolloClientProvider from '@/providers/ApolloClientProvider'
import ToasterProvider from '@/providers/ToasterProvider'

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-montserrat',
})

export const metadata: Metadata = {
  title: 'AI Phone Shop',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const locale = await getLocale()
  const messages = await getMessages()

  return (
    <html lang={locale} suppressHydrationWarning>
      <ApolloClientProvider>
        <NextIntlClientProvider messages={messages}>
          <ThemeProvider attribute="class" defaultTheme="system" disableTransitionOnChange>
            <body className={`${montserrat.variable} antialiased min-h-screen flex flex-col`}>
              <ToasterProvider>
                <AppProgressBar>
                  <Header />
                  <main className="grow pt-[110] pb-[100]">{children}</main>
                  <Footer />
                </AppProgressBar>
              </ToasterProvider>
            </body>
          </ThemeProvider>
        </NextIntlClientProvider>
      </ApolloClientProvider>
    </html>
  )
}
