query GetProductById($productId: String!) {
  getProductById(productId: $productId) {
    id
    title
    price
    brand
    frontCamera
    mainCamera
    ram
    color
    builtInMemory
    processorName
    processorCores
    os
    deliverySet
    materials
    simCount
    simFormat
    images
    battery
    createdAt
    screenDiagonal
    updatedAt
  }
}
